### ISSUE TITLE
Update package.json engines

### ISSUE THREAD

**Issue by rosskukulinski** [jcrugzz/loggly-stream#4]
Installing loggly-stream on current LTS NodeJS (4.x) results in the falling npm warning:
```
WARN engine loggly-stream@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"4.2.4","npm":"2.14.12"})
```

It's probably about time to update the engine field.  Happy to make the PR if you'd accept it.

**Comment by jcrugzz** [comment]
@rosskukulinski totally :+1: on this, will happily accept the PR :)
